# Generated by Django 4.0.3 on 2022-03-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lavacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='status',
            field=models.CharField(choices=[('AB', 'ABERTO'), ('EE', 'EM EXECUCAO'), ('PR', 'PRONTO')], default='AB', max_length=2),
        ),
    ]
